import { consulting } from "../src/index";

/** The same source produces consumer-specific CSS without a runtime dependency. */
export function styles() {
  const { fonts, palette, labs } = consulting;
  const scheme = (value: { light: string; dark: string }) =>
    `light-dark(${value.light}, ${value.dark})`;
  const roles = {
    "font-body": fonts.body,
    "font-display": fonts.display,
    "bg-page": scheme(labs.page),
    "bg-surface": scheme(labs.surface),
    "bg-subtle": scheme(labs.subtle),
    accent: scheme(labs.accent),
  };
  const theme = {
    "color-paper": palette.paper,
    "color-feld": palette.field,
    "color-ink": palette.navy,
    "color-mute": palette.muted,
    "color-rule": palette.rule,
    "color-moss": palette.navy,
    "color-seal": palette.red,
    "color-seal-ink": palette.redText,
    "color-seal-soft": palette.redSoft,
    "color-seal-on-dark": palette.redOnDark,
    "color-brand-navy": palette.navy,
    "color-brand-red": palette.red,
    "font-display": fonts.display,
    "font-body": fonts.body,
  };
  const declarations = (values: Record<string, string>) =>
    Object.entries(values)
      .map(([key, value]) => `    --uix-${key}: ${value};`)
      .join("\n");
  return {
    "labs.css": `/* Generated by brand:generate from src/index.ts. */\n@import "./fonts.css";\n@layer tokens {\n  :root:not([data-brand]), [data-brand="consulting"] {\n${Object.entries(
      roles,
    )
      .map(([key, value]) => `    --uix-${key}: ${value};`)
      .join(
        "\n",
      )}\n  }\n  [data-brand="consulting"] {\n${declarations(consulting.layout)}\n  }\n  [data-brand="consulting"]:not([data-density], [data-density] *) {\n    --uix-density: 1;\n  }\n}\n`,
    "tailwind.css": `/* Generated by brand:generate from src/index.ts. Import after Tailwind. */\n@import "./fonts.css";\n@theme {\n${Object.entries(
      theme,
    )
      .map(([key, value]) => `  --${key}: ${value};`)
      .join("\n")}\n}\n`,
  };
}
