/**
 * The public API surface, per component, as one committed file.
 *
 * Stage 07 asks for "semver applied to components, not the repository. A
 * breaking change to Select is a major for anyone importing Select; the
 * changelog has to say which component."
 *
 * Neither half of that works without being able to answer a smaller
 * question first: **did this component's surface change?** Today the only
 * way to know is to read a diff of implementation and docs together and
 * decide. That is the step this file removes.
 *
 * It reads the emitted `.d.ts` — which is what a consumer's compiler sees,
 * so it is the surface by definition, not an approximation of it — and
 * reduces each component to its exported names and signatures with the
 * prose stripped. Committed, so a change to a component's surface is a
 * line in a diff that a reviewer cannot miss and a release note can cite.
 *
 * Deliberately not the whole `.d.ts`. Those carry every doc comment, so
 * rewording a sentence would look identical to renaming a prop, and a
 * signal that fires on prose is a signal people learn to skim.
 *
 * What this is not: an api-extractor. It does not resolve types across
 * files or compute assignability, so it cannot tell a widening from a
 * narrowing. It tells you *which* component moved, which is the part a
 * changelog needs and a human review does not reliably supply.
 *
 * Usage:
 *   tsx scripts/api-surface.ts            # print
 *   tsx scripts/api-surface.ts check
 *   tsx scripts/api-surface.ts write
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { format } from "prettier";

const TYPES = "dist/packages/ui/components";
const OUT = "packages/ui/api-surface.md";

/** Declaration text with comments and blank lines removed. */
function strip(source: string): string {
  return source
    .replace(/\/\*\*[\s\S]*?\*\//g, "")
    .replace(/\/\/.*$/gm, "")
    .split("\n")
    .map((line) => line.replace(/\s+$/, ""))
    .filter((line) => line.trim().length)
    .join("\n");
}

/**
 * One component's exported surface.
 *
 * Everything `export`ed, with each declaration's body kept so a prop's
 * type is part of the signal. Import lines are dropped: a change from
 * `import type { ReactNode }` to `import { type ReactNode }` is not an
 * API change and would otherwise read as one.
 */
function surface(file: string): string {
  const source = strip(readFileSync(join(TYPES, file), "utf8"));
  const lines = source.split("\n").filter((line) => !/^import\b/.test(line));
  return lines.join("\n").trim();
}

function build(): string {
  const files = readdirSync(TYPES)
    .filter((file) => file.endsWith(".d.ts"))
    .sort();

  const sections = files.map((file) => {
    const name = file.replace(/\.d\.ts$/, "");
    return `## ${name}\n\n\`\`\`ts\n${surface(file)}\n\`\`\``;
  });

  return [
    "# Public API surface",
    "",
    "Generated by `scripts/api-surface.ts` from the emitted declarations, so",
    "this is what a consumer's compiler sees rather than a description of",
    "it. Doc comments are stripped: rewording a sentence must not look like",
    "renaming a prop, or the signal is one people learn to skim.",
    "",
    "A change to a section below is a change to that component's public API.",
    "That is the whole point of committing it — per-component semver needs",
    "someone to be able to answer *which component moved*, and reading a",
    "diff of implementation and prose together does not answer it reliably.",
    "",
    "`nx run ui:api-surface` fails when this file has drifted from the build.",
    "Regenerate with `nx run ui:api-surface-write` and put the change in the",
    "same commit, so the surface and the reason for it travel together.",
    "",
    ...sections,
    "",
  ].join("\n");
}

if (!existsSync(TYPES)) {
  console.log("- api surface: skipped (nothing built)");
  process.exit(0);
}

const serialised = await format(build(), { parser: "markdown", filepath: OUT });
const mode = process.argv[2] ?? "print";

if (mode === "write") {
  writeFileSync(OUT, serialised);
  const count = serialised.match(/^## /gm)?.length ?? 0;
  console.log(`api surface written: ${count} components`);
  process.exit(0);
}

if (mode === "check") {
  const committed = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  if (!committed) {
    console.error(
      "api surface missing. Run `nx run ui:api-surface-write` and commit it.",
    );
    process.exit(1);
  }
  if (committed !== serialised) {
    console.error(
      "api surface changed.\n\n" +
        "  A component's public API is different from the committed one.\n" +
        "  If that is intended, run `nx run ui:api-surface-write`, commit the\n" +
        "  diff in the same change, and say in the message which component\n" +
        "  moved and whether it is breaking — that sentence is the per-\n" +
        "  component semver this file exists to make possible.\n",
    );
    process.exit(1);
  }
  const count = committed.match(/^## /gm)?.length ?? 0;
  console.log(`api surface unchanged — ${count} components`);
  process.exit(0);
}

console.log(serialised);
